version: "3.8"

services:
  db:
    image: mysql:8
    container_name: refeicao
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'refeicao-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3307:3306"
    networks:
      - app_network
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  portainer_data:


networks:
  app_network:
